# YAML Lint Configuration for FinChat-SEC-QA
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments
  comments:
    min-spaces-from-content: 1

  # Trailing spaces
  trailing-spaces: enable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Key duplicates
  key-duplicates: enable

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: true

  # Brackets and braces
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # Colons
  colons:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Commas
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Hyphens
  hyphens:
    max-spaces-after: 1

  # Key ordering
  key-ordering: disable

  # Octal values
  octal-values: enable

  # Quoted strings
  quoted-strings:
    quote-type: any
    required: only-when-needed

# Ignore patterns
ignore: |
  .venv/
  venv/
  node_modules/
  .git/
  docs/_build/
  htmlcov/
  .tox/
  build/
  dist/
  *.egg-info/