[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "finchat_sec_qa"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
    "requests",
    "scikit-learn",
    "numpy",
    "vaderSentiment",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["finchat", "finchat_sec_qa"]
