[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "finchat"
version = "0.0.0"
description = "FinChat SEC QA"
authors = [{name = "FinChat", email = "dev@example.com"}]
requires-python = ">=3.9"
